Various fixes

diff --git a/bin/fzfp b/bin/fzfp
--- a/bin/fzfp
+++ b/bin/fzfp
@@ -1,8 +1,13 @@
 #!/usr/bin/env sh
 
-op="${1:--c}"; shift >&2 2>/dev/null
-cd ~/.password-store || { echo "Could not cd to ~/.password-store"; exit 1; }
-pp="$(fd gpg | sd ".gpg" "" | fzf --height 40%)"
-echo "pass $op $pp"
-pass "$op" "$@" "$pp"
-cd - || return 1
+FZFP_PASS_CMD="pass"
+FZFP_PASS_DIR="$HOME/.password-store"
+
+FZFP_HEIGHT="${FZFP_HEIGHT:-40%}"
+FZFP_PROMPT="${FZFP_PROMPT:-"$FZFP_PASS_CMD@$FZFP_PASS_DIR> "}"
+FZFP_PASS_OPTS="${FZFP_PASS_OPTS:-}"
+cd "$FZFP_PASS_DIR" || { echo "Could not cd to $FZFP_PASS_DIR" >&2; exit 1; }
+pp="$(fd gpg | sd ".gpg" "" | fzf --height "$FZFP_HEIGHT" --prompt "$FZFP_PROMPT")"
+"${FZFP_PASS_CMD}" $FZFP_PASS_OPTS "$@" "$pp"
+cd - >/dev/null || return 1
+
