Improve backup scripts

diff --git a/common/bin/backupify b/common/bin/backupify
--- a/common/bin/backupify
+++ b/common/bin/backupify
@@ -33,12 +33,18 @@ pushd (dirname $target) >/dev/null
 
 	set remote_path "$BACKUP_REMOTE_DIR/$backup_file_name$BACKUP_FILE_EXT"
 	echo "Streaming PGP encrypted backup of $friendly_target to SSH host $BACKUP_REMOTE_HOST at $remote_path"
-	ssh $BACKUP_REMOTE_HOST "mkdir -p $BACKUP_REMOTE_DIR"
+	ssh $BACKUP_REMOTE_HOST "mkdir -p $BACKUP_REMOTE_DIR" || begin
+		echo "Failed to SSH to $BACKUP_REMOTE_HOST and create remote dir $BACKUP_REMOTE_DIR"
+		exit 3
+	end
 	# TODO: progress indicator?
 	tar cf - . |
 		zstd --ultra -T2 -22 |
 		gpg --encrypt --recipient daniel@lyte.dev |
-		ssh $BACKUP_REMOTE_HOST "cat - > $remote_path"
+		ssh $BACKUP_REMOTE_HOST "cat - > $remote_path" || begin
+			echo "Failed to stream backup"
+			exit 4
+		end
 popd >/dev/null
 
 # TODO: checksum?
diff --git a/common/bin/unbackupify b/common/bin/unbackupify
--- a/common/bin/unbackupify
+++ b/common/bin/unbackupify
@@ -21,6 +21,16 @@ else if test (count $argv) -lt 1
 	exit 1
 end
 
+ssh $BACKUP_REMOTE_HOST "echo 1" &>/dev/null || begin
+	echo "Cannot ssh to $BACKUP_REMOTE_HOST"
+	exit 6
+end
+
+ssh $BACKUP_REMOTE_HOST "test -d $BACKUP_REMOTE_DIR/$target" || begin
+	echo "Remote directory $BACKUP_REMOTE_DIR/$target does not exist on $BACKUP_REMOTE_HOST (use --list-backup-files to show)"
+	exit 5
+end
+
 # TODO: autocomplete?
 # TODO: checksum?
 # TODO: progress indicator?
@@ -36,7 +46,10 @@ pushd $local_dir >/dev/null
 	ssh $BACKUP_REMOTE_HOST "cat $BACKUP_REMOTE_DIR/$target" |
 		gpg --decrypt 2>/dev/null |
 		zstd --ultra -T2 -22 -dc |
-		tar -xf -
+		tar -xf - || begin
+			echo "Failed to stream backup"
+			exit 4
+		end
 
 popd >/dev/null
 
