Lots of small fixes I've forgotten to commit

diff --git a/common/bin/kubfn b/common/bin/kubfn
--- a/common/bin/kubfn
+++ b/common/bin/kubfn
@@ -1,4 +1,9 @@
 #!/usr/bin/env sh
+has_command kubectl || {
+	echo "kubectl command not found"
+	exit 1
+}
+
 kubectl get namespaces --show-labels | \
 	uniq | \
 	sort | \
